################################################################################
# Copyright 2019 ntno                                                          #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: deploy-scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: deploy-scripts/before_install
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy-scripts/after_install
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy-scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: deploy-scripts/stop_server
      timeout: 300
      runas: ec2-user

