version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: deploy-scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: deploy-scripts/before_install
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy-scripts/after_install
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy-scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: deploy-scripts/stop_server
      timeout: 300
      runas: ec2-user

