#!/bin/bash
################################################################################
# Copyright 2019 ntno                                                          #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

#stop the docker service and remove local-kv.db to avoid 'port in use' errors
sudo service docker stop
sudo rm /var/lib/docker/network/files/local-kv.db

#restart docker
sudo service docker start

#debugging
echo "DEPLOYMENT_GROUP_ID: " $DEPLOYMENT_GROUP_ID
echo "DEPLOYMENT_ID: " $DEPLOYMENT_ID
echo "DEPLOYMENT_GROUP_NAME: " $DEPLOYMENT_GROUP_NAME
echo "APPLICATION_NAME: " $APPLICATION_NAME




