#!/bin/bash
################################################################################
# Copyright 2019 ntno                                                          #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################


#debugging
echo "DEPLOYMENT_GROUP_ID: " $DEPLOYMENT_GROUP_ID
echo "DEPLOYMENT_ID: " $DEPLOYMENT_ID
echo "DEPLOYMENT_GROUP_NAME: " $DEPLOYMENT_GROUP_NAME
echo "APPLICATION_NAME: " $APPLICATION_NAME
echo "DEPLOYMENT_IMAGE_ID: " $DEPLOYMENT_IMAGE_ID

DEPLOYMENT_IMAGE_ID=$(cat /home/ec2-user/image-name.txt)
LOG_GROUP_NAME=$(cat /home/ec2-user/log-group-name.txt)
echo "DEPLOYMENT_IMAGE_ID: " $DEPLOYMENT_IMAGE_ID
echo "LOG_GROUP_NAME: " $LOG_GROUP_NAME

#start container with open ports 443 and 80
#send logs to the specified cloudwatch log group
docker run \
--log-driver=awslogs --log-opt awslogs-group=$LOG_GROUP_NAME \
--name $DEPLOYMENT_ID \
-p 443:443 \
-p 80:80 \
-d \
$DEPLOYMENT_IMAGE_ID