#!/bin/bash
#debugging
echo "DEPLOYMENT_GROUP_ID: " $DEPLOYMENT_GROUP_ID
echo "DEPLOYMENT_ID: " $DEPLOYMENT_ID
echo "DEPLOYMENT_GROUP_NAME: " $DEPLOYMENT_GROUP_NAME
echo "APPLICATION_NAME: " $APPLICATION_NAME

name=$DEPLOYMENT_ID
if [[ $(docker ps --filter "name=^/$name$" --format '{{.Names}}') == $name ]] ; then
    echo "found $name"
    echo "stopping $name"
    docker stop $name
    echo "removing $name"
    docker rm $name
fi
