################################################################################
# Copyright 2019 ntno                                                          #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: creates s3 bucket with default encryption
Parameters:
  CustomBucketName:
    Type: String
    Description: name for the bucket
    AllowedPattern: ^[a-z0-9][a-z0-9\-]{1,61}[a-z0-9]$
    ConstraintDescription: name must be between 3 and 63 characters long and may contain lowercase alphanumerics and dashes
    #NOTE - this is a custom constraint for this template - see amazon docs for full notes on S3 bucket naming requirements
    #https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html
  DomainTag:
    Type: String
    Description: resource tag for organization
Resources:
  CustomBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      BucketEncryption: 
          ServerSideEncryptionConfiguration: 
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'aws:kms'
      BucketName: !Ref CustomBucketName
      Tags: 
        - 
          Key: "domain"
          Value: !Ref DomainTag
  CustomBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CustomBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: 
              - !Sub 'arn:aws:s3:::${CustomBucketName}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'aws:kms'
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: 
              - !Sub 'arn:aws:s3:::${CustomBucketName}/*'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': True
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Sub 'arn:aws:s3:::${CustomBucketName}/*'
            Condition:
              Bool:
                'aws:SecureTransport': False
