AWSTemplateFormatVersion: 2010-09-09
Description: creates s3 bucket with default encryption
Parameters:
  CustomBucketName:
    Type: String
    Description: name for the bucket
    AllowedPattern: ^[a-z0-9][a-z0-9\-]{1,61}[a-z0-9]$
    ConstraintDescription: name must be between 3 and 63 characters long and may contain lowercase alphanumerics and dashes
    #NOTE - this is a custom constraint for this template - see amazon docs for full notes on S3 bucket naming requirements
    #https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html
Resources:
  CustomBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      BucketEncryption: 
          ServerSideEncryptionConfiguration: 
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      BucketName: !Ref CustomBucketName
  CustomBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CustomBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: 
              - !Sub 'arn:aws:s3:::${CustomBucketName}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'aws:kms'
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: 
              - !Sub 'arn:aws:s3:::${CustomBucketName}/*'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': True
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Sub 'arn:aws:s3:::${CustomBucketName}/*'
            Condition:
              Bool:
                'aws:SecureTransport': False
