AWSTemplateFormatVersion: 2010-09-09
Description: creates code commit repository and sns trigger topic 
Parameters:
  RepoName:
    Type: String
    Description: repository name
  RepoDescription:
    Type: String
    Description: repository description
Resources:
  TriggerSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Sub "${RepoName}-SNS"
      # KmsMasterKeyId: String
      # Subscription: 
      #   - Subscription
      # TopicName: String
  CodeRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: !Ref RepoDescription
      Triggers:
      - Name: MasterTrigger
        DestinationArn:
          Ref: TriggerSNS
        Branches:
        - master            #empty array to trigger on all branches
        Events:
        - all
  ImageRepo:
    Type: AWS::ECR::Repository
    Properties: 
      # LifecyclePolicy: 
      #   LifecyclePolicy
      RepositoryName: !Ref RepoName
      RepositoryPolicyText: 
        Version: 2012-10-17
        Statement:
          - Sid: DenyPushForAllUsers
            Effect: Deny
            Principal:
              AWS:
                - '*'
            Action:
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
      Tags: 
        - 
          Key: "domain"
          Value: "personal"
        - 
          Key: "project"
          Value: "ntno-challenge"
