AWSTemplateFormatVersion: 2010-09-09
Description: creates code commit repository and sns trigger topic 
Parameters:
  RepoName:
    Type: String
    Description: repository name
  RepoDescription:
    Type: String
    Description: repository description
Resources:
  TriggerSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Sub "${RepoName}-SNS"
      # KmsMasterKeyId: String
      # Subscription: 
      #   - Subscription
      # TopicName: String
  CodeRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: !Ref RepoDescription
      Triggers:
      - Name: MasterTrigger
        DestinationArn:
          Ref: TriggerSNS
        Branches:
        - master            #empty array to trigger on all branches
        Events:
        - all
  ImageRepo:
    Type: AWS::ECR::Repository
    Properties: 
      # LifecyclePolicy: 
      #   LifecyclePolicy
      RepositoryName: !Ref RepoName
      RepositoryPolicyText: 
        Version: 2012-10-17
        Statement:
          - Sid: DenyPushForAllUsers
            Effect: Deny
            Principal:
              AWS:
                - '*'
            Action:
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
      Tags: 
        - 
          Key: "domain"
          Value: "personal"
        - 
          Key: "project"
          Value: "ntno-challenge"
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      RoleName: !Sub 'codebuild-${RepoName}-service-role'
      Policies: 
        - PolicyName: 'CodeBuildPermissions'
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Sid: CreateLogsPermission
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${RepoName}'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${RepoName}:*'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
              # - Sid: WriteToCodePipelineBucketPermission
              #   Effect: Allow
              #   Resource:
              #     - !Sub 'arn:aws:s3:::codepipeline-${AWS::Region}-*'
              #   Action:
              #     - 's3:PutObject'
              #     - 's3:GetObject'
              #     - 's3:GetObjectVersion'
              #     - 's3:GetBucketAcl'
              #     - 's3:GetBucketLocation'
              - Sid: PullFromCodeCommitRepoPermission
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}'
                Action:
                  - 'codecommit:GitPull'
              - Sid: ReadWriteToEcrRepo
                Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:GetRepositoryPolicy'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:ListImages'
                  - 'ecr:DescribeImages'
                  - 'ecr:BatchGetImage'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:PutImage'
                Resource: 
                  - !GetAtt 
                    - ImageRepo
                    - Arn
                  
