#!/bin/bash
################################################################################
# Copyright 2019 ntno                                                          #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################


#debugging
echo "overwriting dumm-cert.pem and dummy-key.pem with parameter store values"

#TODO parameterize param names, pass via pipeline cft
aws ssm get-parameter --name '/hello-world/cert.pem'  --with-decryption --output text --query Parameter.Value > dummy-cert.pem
aws ssm get-parameter --name '/hello-world/key.pem'  --with-decryption --output text --query Parameter.Value > dummy-key.pem